# netlify.toml

[build]
  # This tells Netlify where your main site files are.
  # If your HTML files are at the root, you don't need to set a publish directory.
  
  # This tells Netlify where your serverless functions are.
  # This path must be correct.
  functions = "netlify/functions"

# This section explicitly configures the function builder.
[functions]
  node_bundler = "esbuild"