# This is the configuration file for Netlify.
[functions]
  directory = "netlify/functions/"

# This rule protects the downloads page.
# It forces any visitor to log in before they can see the content.
[[redirects]]
  from = "/downloads"
  to = "/downloads.html"
  status = 200
  force = true
  conditions = {Role = ["admin", "editor", "reader"]}

# This rule handles users who are not logged in.
[[redirects]]
  from = "/downloads"
  to = "/" # Redirect them to the homepage
  status = 401
  force = true