# netlify.toml

[build]
  # This is the correct line. It tells Netlify that your
  # serverless functions are in a folder named "functions".
  functions = "functions"

# This is the missing redirect rule. It tells the server to
# forward any request from "/api/..." to your actual function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200